name: Shell Command Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_shell_command:
    runs-on: ubuntu-latest   # OR runs-on: ${{ matrix.os }}
                             #     strategy:        if you want to run the same command on diff OS
                              #      matrix:
                               #       os: [list of the os]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run-shell-command
      run: |
        echo "Hello, world!"
        node -v
        pwd
        ls
  run-windows-commands:
    runs-on: windows-latest
    needs: ["Run-shell-command"]
  
    steps:
    - name: Run shell command
      run: |
       echo "Hello, world!"
       echo %USERNAME%
       echo "Hello, world!"
    - name: get directory
      run: dir